config/routes.rb
Rails.application.routes.draw do

  root 'orden_compras#index'
  resources :orden_compras
  resources :articulos
  resources :movimiento_inventarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/movimiento_inventario.rb
class MovimientoInventario
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated
  field :codigo_movimiento, type: String
  field :tipo_movimiento, type: String
  field :codigo_articulo, type: String
  field :cantidad, type: Integer
end

app/controllers/movimiento_inventarios_controller.rb
class MovimientoInventariosController < ApplicationController
  before_action :set_movimiento_inventario, only: [:show, :edit, :update, :destroy]

  # GET /movimiento_inventarios
  # GET /movimiento_inventarios.json
  def index
    @movimiento_inventarios = MovimientoInventario.all
  end

  # GET /movimiento_inventarios/1
  # GET /movimiento_inventarios/1.json
  def show
  end

  # GET /movimiento_inventarios/new
  def new
    @movimiento_inventario = MovimientoInventario.new
  end

  # GET /movimiento_inventarios/1/edit
  def edit
  end

  # POST /movimiento_inventarios
  # POST /movimiento_inventarios.json
  def create
    @movimiento_inventario = MovimientoInventario.new(movimiento_inventario_params)
    @movimiento_inventario.codigo_movimiento = Faker::Code.unique.ean

    art = Articulo.find_by(codigo_articulo: @movimiento_inventario.codigo_articulo)

    if @movimiento_inventario.tipo_movimiento=="ENTRADA"
      art.total_inventario += @movimiento_inventario.cantidad
      art.save!
    else
      art.total_inventario -= @movimiento_inventario.cantidad
      art.save!
    end


    respond_to do |format|
      if @movimiento_inventario.save
        format.html { redirect_to @movimiento_inventario, notice: 'Movimiento inventario was successfully created.' }
        format.json { render :show, status: :created, location: @movimiento_inventario }
      else
        format.html { render :new }
        format.json { render json: @movimiento_inventario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movimiento_inventarios/1
  # PATCH/PUT /movimiento_inventarios/1.json
  def update
    respond_to do |format|
      if @movimiento_inventario.update(movimiento_inventario_params)
        format.html { redirect_to @movimiento_inventario, notice: 'Movimiento inventario was successfully updated.' }
        format.json { render :show, status: :ok, location: @movimiento_inventario }
      else
        format.html { render :edit }
        format.json { render json: @movimiento_inventario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movimiento_inventarios/1
  # DELETE /movimiento_inventarios/1.json
  def destroy
    Articulo.find_by(codigo_articulo: @movimiento_inventario.codigo_articulo)
    @movimiento_inventario.destroy
    respond_to do |format|
      format.html { redirect_to movimiento_inventarios_url, notice: 'Movimiento inventario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movimiento_inventario
      @movimiento_inventario = MovimientoInventario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movimiento_inventario_params
      params.require(:movimiento_inventario).permit(:codigo_movimiento, :codigo_almacen, :tipo_movimiento, :codigo_articulo, :cantidad)
    end
end

app/helpers/movimiento_inventarios_helper.rb
module MovimientoInventariosHelper
end

app/views/movimiento_inventarios/_form.html.erb
<%= form_for(movimiento_inventario) do |f| %>
  <% if movimiento_inventario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movimiento_inventario.errors.count, "error") %> prohibited this movimiento_inventario from being saved:</h2>

      <ul>
      <% movimiento_inventario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :tipo_movimiento %>
    <%= f.select :tipo_movimiento, options_for_select(["ENTRADA", "SALIDA"], "ENTRADA"), {}, {class: 'form-control'} %>
  </div>

    <div class="form-group">
      <%= f.label :codigo_articulo %>
      <%= f.select(:codigo_articulo, Articulo.all.collect {|a| [a.descripcion, a.codigo_articulo]}, {:prompt => "Please select"},
                   {class: 'form-control'}) -%>
    </div>

  <div class="form-group">
    <%= f.label :cantidad %>
    <%= f.number_field :cantidad, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movimiento_inventarios/edit.html.erb
<h1>Editing Movimiento Inventario</h1>

<%= render 'form', movimiento_inventario: @movimiento_inventario %>

<%= link_to 'Show', @movimiento_inventario %> |
<%= link_to 'Back', movimiento_inventarios_path %>

app/views/movimiento_inventarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movimiento Inventarios</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Codigo movimiento</th>
      <th>Tipo movimiento</th>
      <th>Codigo articulo</th>
      <th>Cantidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movimiento_inventarios.each do |movimiento_inventario| %>
      <tr>
        <td><%= movimiento_inventario.codigo_movimiento %></td>
        <td><%= movimiento_inventario.tipo_movimiento %></td>
        <td><%= movimiento_inventario.codigo_articulo %></td>
        <td><%= movimiento_inventario.cantidad %></td>
        <td><%= link_to 'Show', movimiento_inventario %></td>
        <td><%= link_to 'Edit', edit_movimiento_inventario_path(movimiento_inventario) %></td>
        <td><%= link_to 'Destroy', movimiento_inventario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movimiento Inventario', new_movimiento_inventario_path, class: 'btn btn-primary' %>

app/views/movimiento_inventarios/new.html.erb
<h1>New Movimiento Inventario</h1>

<%= render 'form', movimiento_inventario: @movimiento_inventario %>

<%= link_to 'Back', movimiento_inventarios_path %>

app/views/movimiento_inventarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo movimiento:</strong>
  <%= @movimiento_inventario.codigo_movimiento %>
</p>


<p>
  <strong>Tipo movimiento:</strong>
  <%= @movimiento_inventario.tipo_movimiento %>
</p>

<p>
  <strong>Codigo articulo:</strong>
  <%= @movimiento_inventario.codigo_articulo %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @movimiento_inventario.cantidad %>
</p>

<%= link_to 'Edit', edit_movimiento_inventario_path(@movimiento_inventario) %> |
<%= link_to 'Back', movimiento_inventarios_path %>