config/routes.rb
Rails.application.routes.draw do

  root 'orden_compras#index'
  resources :orden_compras
  resources :articulos
  resources :movimiento_inventarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/orden_compra.rb
require 'pp'
class OrdenCompra
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated
  field :codigo_orden, type: String
  field :fecha_orden, type: DateTime
  field :monto_total, type: Integer
  field :articulos, type: Array


  validates :monto_total, presence: true
  validate :date_cannot_be_in_the_past

  def date_cannot_be_in_the_past
    if fecha_orden.present? && fecha_orden < Date.today
      errors.add(:fecha_orden, "can't be in the past")
    end
  end


  def articulos_for_form=(value_from_form)
    value_from_form = "" unless value_from_form.respond_to(:split)
    self.articulos = value_from_form.split(',')
  end

  def articulos_for_form
    self.articulos
  end


  def total_de_la_orden
    sum=0
    self.articulos.each do |x|
      sum+= x[:suplidor][:precio_compra]
    end
    sum
  end


end

app/controllers/orden_compras_controller.rb
class OrdenComprasController < ApplicationController
  before_action :set_orden_compra, only: [:show, :edit, :update, :destroy]

  # GET /orden_compras
  # GET /orden_compras.json
  def index
    @orden_compras = OrdenCompra.all
  end

  # GET /orden_compras/1
  # GET /orden_compras/1.json
  def show
  end

  # GET /orden_compras/new
  def new
    @orden_compra = OrdenCompra.new
  end

  # GET /orden_compras/1/edit
  def edit
  end

  # POST /orden_compras
  # POST /orden_compras.json
  def create
    @orden_compra = OrdenCompra.new(orden_compra_params)
    # @orden_compra.fecha_orden ||= Date.today


    formated_date = Date.new(orden_compra_params["fecha_orden(1i)"].to_i,
                             orden_compra_params["fecha_orden(2i)"].to_i,
                             orden_compra_params["fecha_orden(3i)"].to_i)
    @orden_compra.fecha_orden =formated_date


    @orden_compra.codigo_orden = Faker::Code.unique.ean
    lista_articulos = []
    @orden_compra.articulos.each do |art|
      if art != ""
        articulo = Articulo.find_by(codigo_articulo: art)
        menor_tiempo = (formated_date - Date.today).to_i
        precio_actual = 9999
        suplidor_selecionado = nil
        articulo.suplidores.each do |suplidor|
          if suplidor[:tiempo_entrega] < menor_tiempo
            if suplidor[:precio_compra] < precio_actual
              suplidor_selecionado= suplidor
              precio_actual = suplidor[:precio_compra]
            end
          end
        end

        lista_articulos.push(
            codigo_articulo: articulo.codigo_articulo,
            cantidad: @orden_compra.monto_total,
            suplidor: suplidor_selecionado || articulo.suplidores[0]
        )
      end

    end
    @orden_compra.articulos = lista_articulos


    respond_to do |format|
      if @orden_compra.save
        format.html {redirect_to @orden_compra, notice: 'Orden compra was successfully created.'}
        format.json {render :show, status: :created, location: @orden_compra}
      else
        format.html {render :new}
        format.json {render json: @orden_compra.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /orden_compras/1
  # PATCH/PUT /orden_compras/1.json
  def update

    formated_date = Date.new(orden_compra_params["fecha_orden(1i)"].to_i,
                             orden_compra_params["fecha_orden(2i)"].to_i,
                             orden_compra_params["fecha_orden(3i)"].to_i)

    orden_compra_params[:fecha_orden]=formated_date

    respond_to do |format|
      if @orden_compra.update(orden_compra_params)
        format.html {redirect_to @orden_compra, notice: 'Orden compra was successfully updated.'}
        format.json {render :show, status: :ok, location: @orden_compra}
      else
        format.html {render :edit}
        format.json {render json: @orden_compra.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /orden_compras/1
  # DELETE /orden_compras/1.json
  def destroy
    @orden_compra.destroy
    respond_to do |format|
      format.html {redirect_to orden_compras_url, notice: 'Orden compra was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_orden_compra
    @orden_compra = OrdenCompra.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def orden_compra_params
    params.require(:orden_compra).permit(:codigo_orden, :codigo_suplidor, "fecha_orden(1i)".to_sym, "fecha_orden(1i)".to_sym, "fecha_orden(1i)".to_sym, :fecha_orden, :monto_total, :articulos => [])
  end
end

app/helpers/orden_compras_helper.rb
module OrdenComprasHelper
end

app/views/orden_compras/_form.html.erb
<%= form_for(orden_compra) do |f| %>
  <% if orden_compra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(orden_compra.errors.count, "error") %> prohibited this orden_compra from being saved:</h2>

      <ul>
      <% orden_compra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :fecha_orden %>
    <%= f.date_select :fecha_orden, selected: Date.today, min: Date.today, max: 3.months.from_now %>
  </div>

  <div class="form-group">
    <%= f.label :monto_total %>
    <%= f.number_field :monto_total, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :articulos %>
    <%= f.select(:articulos, Articulo.all.collect {|a| [a.descripcion, a.codigo_articulo]}, {:prompt => "Please select"},
                 {:multiple => true, :size => 5, class: 'form-control'}) -%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orden_compras/edit.html.erb
<h1>Editing Orden Compra</h1>

<%= render 'form', orden_compra: @orden_compra %>

<%= link_to 'Show', @orden_compra %> |
<%= link_to 'Back', orden_compras_path %>

app/views/orden_compras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orden Compras</h1>

<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>Codigo orden</th>
    <th>Fecha orden</th>
    <th>Cantidad articulos</th>
    <th>Costo Total $</th>
    <th>Articulos</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @orden_compras.each do |orden_compra| %>
      <tr>
        <td><%= orden_compra.codigo_orden %></td>
        <td><%= orden_compra.fecha_orden %></td>
        <td><%= orden_compra.monto_total %></td>
        <td><%= orden_compra.total_de_la_orden %></td>
        <td>
          <% orden_compra.articulos.each do |x| %>
              <pre><%= JSON.pretty_generate(x) %></pre>
          <% end %>
        </td>
        <td><%= link_to 'Show', orden_compra %></td>
        <td><%#= link_to 'Edit', edit_orden_compra_path(orden_compra) %></td>
        <td><%= link_to 'Destroy', orden_compra, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Orden Compra', new_orden_compra_path, class: 'btn btn-primary' %>

app/views/orden_compras/new.html.erb
<h1>New Orden Compra</h1>

<%= render 'form', orden_compra: @orden_compra %>

<%= link_to 'Back', orden_compras_path %>

app/views/orden_compras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo orden:</strong>
  <%= @orden_compra.codigo_orden %>
</p>

<p>
  <strong>Fecha orden:</strong>
  <%= @orden_compra.fecha_orden %>
</p>

<p>
  <strong>Monto total:</strong>
  <%= @orden_compra.monto_total %>
</p>

<p>
  <strong>Articulos:</strong>
  <% @orden_compra.articulos.each do |x| %>
    <pre><%= JSON.pretty_generate(x) %></pre>
<% end %>
</p>

<%= link_to 'Edit', edit_orden_compra_path(@orden_compra) %> |
<%= link_to 'Back', orden_compras_path %>