config/routes.rb
Rails.application.routes.draw do

  root 'orden_compras#index'
  resources :orden_compras
  resources :articulos
  resources :movimiento_inventarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/articulo.rb
class Articulo
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated
  field :codigo_articulo, type: String
  field :descripcion, type: String
  field :unidad_compra_diaria, type: Integer
  field :total_inventario, type: Integer
  field :suplidores, type: Array


  def fecha_de_acabado
    self.total_inventario/self.unidad_compra_diaria
  end

  index({codigo_articulo: 1}, {unique: true})

end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  before_action :set_articulo, only: [:show, :edit, :update, :destroy]

  # GET /articulos
  # GET /articulos.json
  def index
    @articulos = Articulo.all
  end

  # GET /articulos/1
  # GET /articulos/1.json
  def show
  end

  # GET /articulos/new
  def new
    @articulo = Articulo.new
  end

  # GET /articulos/1/edit
  def edit
  end

  # POST /articulos
  # POST /articulos.json
  def create
    @articulo = Articulo.new(articulo_params)

    respond_to do |format|
      if @articulo.save
        format.html { redirect_to @articulo, notice: 'Articulo was successfully created.' }
        format.json { render :show, status: :created, location: @articulo }
      else
        format.html { render :new }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articulos/1
  # PATCH/PUT /articulos/1.json
  def update
    respond_to do |format|
      if @articulo.update(articulo_params)
        format.html { redirect_to @articulo, notice: 'Articulo was successfully updated.' }
        format.json { render :show, status: :ok, location: @articulo }
      else
        format.html { render :edit }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articulos/1
  # DELETE /articulos/1.json
  def destroy
    @articulo.destroy
    respond_to do |format|
      format.html { redirect_to articulos_url, notice: 'Articulo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_articulo
      @articulo = Articulo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def articulo_params
      params.require(:articulo).permit(:codigo_articulo, :descripcion, :unidad_compra_diaria, :total_inventario)
    end
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/views/articulos/_form.html.erb
<%= form_for(articulo) do |f| %>
  <% if articulo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(articulo.errors.count, "error") %> prohibited this articulo from being saved:</h2>

      <ul>
      <% articulo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :codigo_articulo %>
    <%= f.text_field :codigo_articulo %>
  </div>

  <div class="form-group">
    <%= f.label :descripcion %>
    <%= f.text_field :descripcion %>
  </div>

  <div class="form-group">
    <%= f.label :unidad_compra_diaria %>
    <%= f.text_field :unidad_compra_diaria %>
  </div>

    <div class="form-group">
      <%= f.label :total_inventario %>
      <%= f.text_field :total_inventario %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articulos/edit.html.erb
<h1>Editing Articulo</h1>

<%= render 'form', articulo: @articulo %>

<%= link_to 'Show', @articulo %> |
<%= link_to 'Back', articulos_path %>

app/views/articulos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articulos</h1>

<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>Codigo articulo</th>
    <th>Descripcion</th>
    <th>Unidad compra diaria</th>
    <th>Total Inventario</th>
    <th>Se acabara en:</th>
    <th>Suplidores</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @articulos.each do |articulo| %>
      <tr>
        <td><%= articulo.codigo_articulo %></td>
        <td><%= articulo.descripcion %></td>
        <td><%= articulo.unidad_compra_diaria %></td>
        <td><%= articulo.total_inventario %></td>
        <td><%= articulo.fecha_de_acabado %> Dias</td>

        <td>
          <% if articulo.suplidores.respond_to? :each %>
              <% articulo.suplidores.each do |x| %>
                  <pre><%= JSON.pretty_generate(x) %></pre>
              <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', articulo %></td>
        <td><%= link_to 'Edit', edit_articulo_path(articulo) %></td>
        <td><%= link_to 'Destroy', articulo, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Articulo', new_articulo_path, class: 'btn btn-primary' %>

app/views/articulos/new.html.erb
<h1>New Articulo</h1>

<%= render 'form', articulo: @articulo %>

<%= link_to 'Back', articulos_path %>

app/views/articulos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo articulo:</strong>
  <%= @articulo.codigo_articulo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @articulo.descripcion %>
</p>



<p>
  <strong>Unidad compra diaria:</strong>
  <%= @articulo.unidad_compra_diaria %>
</p>


<p>
  <strong>Total en inventario:</strong>
  <%= @articulo.total_inventario %>
</p>

<p>
  <strong>Suplidores:</strong>
  <% if @articulo.suplidores.respond_to? :each %>
      <% @articulo.suplidores.each do |x| %>
        <pre><%= JSON.pretty_generate(x) %></pre>
    <% end %>
<% end %>

<p>

  <%= link_to 'Edit', edit_articulo_path(@articulo) %> |
<%= link_to 'Back', articulos_path %>